(() => {
  const STORAGE='hb-smos-nexus-v1', AUTH='hb-smos-auth', PASS='BudaOps1!';
  const TARGETS={visits:6,coaching:8};
  const MISSIONS={
    0:{headline:'System Reset + Week Preview',detail:'Clear bandwidth. Lock Monday priorities.',tasks:[{id:'s1',title:'Scan open actions'},{id:'s2',title:'Confirm Monday crews'},{id:'s3',title:'Set leadership intention'}]},
    1:{headline:'Plan Align Deploy',detail:'Set weekly tempo.',tasks:[{id:'m1',title:'Leadership huddle'},{id:'m2',title:'Publish visit targets'},{id:'m3',title:'Clear weekend escalations'},{id:'m4',title:'Log first coaching or visit'}]},
    2:{headline:'Crew Visits + Coaching',detail:'Be visible.',tasks:[{id:'t1',title:'Complete 2 crew visits'},{id:'t2',title:'Log safety or quality obs'},{id:'t3',title:'One formal coaching'},{id:'t4',title:'Update open actions'}]},
    3:{headline:'Interviews and Process',detail:'Pipeline + systems.',tasks:[{id:'w1',title:'Interview or pipeline review'},{id:'w2',title:'Process friction check'},{id:'w3',title:'Targeted coaching'},{id:'w4',title:'Short field visit'}]},
    4:{headline:'Close Gaps',detail:'Drive unfinished actions.',tasks:[{id:'th1',title:'Close high-priority actions'},{id:'th2',title:'Catch-up visits if behind'},{id:'th3',title:'QA documentation check'},{id:'th4',title:'Coach recurring deficiencies'}]},
    5:{headline:'Lock Results',detail:'Hit remaining targets.',tasks:[{id:'f1',title:'Close visit gap'},{id:'f2',title:'Final coaching'},{id:'f3',title:'Weekend coverage'},{id:'f4',title:'Revenue / labor signals'}]},
    6:{headline:'Score the Week',detail:'What moved. What slipped.',tasks:[{id:'sa1',title:'Complete weekly review'},{id:'sa2',title:'Score People / Field / Systems'},{id:'sa3',title:'Top 3 carry-forward actions'},{id:'sa4',title:'Recovery + next intention'}]}
  };
  let state={tasks:{},coaching:[],visits:[],actions:[],selectedDay:new Date().getDay(),unlocked:false};
  try{const raw=localStorage.getItem(STORAGE); if(raw) Object.assign(state, JSON.parse(raw), {unlocked:sessionStorage.getItem(AUTH)==='1'});}catch(e){}
  state.selectedDay=new Date().getDay();
  const save=()=>{const s=Object.assign({},state); delete s.unlocked; localStorage.setItem(STORAGE,JSON.stringify(s));};
  const $=id=>document.getElementById(id);
  function setUnlocked(v){state.unlocked=v; if(v) sessionStorage.setItem(AUTH,'1'); else sessionStorage.removeItem(AUTH); $('lockState').textContent=v?'UNLOCKED':'LOCKED'; $('unlockBtn').classList.toggle('hid',v); $('lockBtn').classList.toggle('hid',!v);}
  function weekStart(){const s=new Date();s.setHours(0,0,0,0);const d=s.getDay();s.setDate(s.getDate()-(d===0?6:d-1));return s;}
  const thisWeek=arr=>arr.filter(e=>new Date(e.ts)>=weekStart());
  function metrics(){const visits=thisWeek(state.visits).length, coaching=thisWeek(state.coaching).length, openActions=state.actions.filter(a=>!a.done).length; const tasks=MISSIONS[state.selectedDay].tasks; const map=state.tasks[String(state.selectedDay)]||{}; const done=tasks.filter(t=>map[t.id]).length; return {visits,coaching,openActions,weekPct:tasks.length?Math.round(done/tasks.length*100):0};}
  function updateUI(){const m=metrics(); $('weekPct').textContent=m.weekPct+'%'; $('visitsMetric').textContent=m.visits; $('coachMetric').textContent=m.coaching; $('actionsMetric').textContent=m.openActions; $('focusText').textContent=m.visits<TARGETS.visits?('Field pressure: '+m.visits+'/6 visits.'):(m.coaching<TARGETS.coaching?('People gap: '+m.coaching+'/8 coaching.'):(m.openActions>3?('Systems drag: '+m.openActions+' open actions.'):'Rhythm is solid. Raise QA documentation.'));}
  function renderDays(){const names=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']; $('dayStrip').innerHTML=names.map((n,i)=>'<button class="chip'+(i===state.selectedDay?' on':'')+'" data-day="'+i+'">'+n+'</button>').join(''); $('dayStrip').querySelectorAll('.chip').forEach(b=>b.onclick=()=>{state.selectedDay=+b.dataset.day;renderDays();renderMission();updateUI();});}
  function renderMission(){const m=MISSIONS[state.selectedDay]; $('missionHeadline').textContent=m.headline; $('missionDetail').textContent=m.detail; const key=String(state.selectedDay); if(!state.tasks[key]) state.tasks[key]={}; const map=state.tasks[key]; $('taskList').innerHTML=m.tasks.map(t=>'<div class="task '+(map[t.id]?'done':'')+'" data-id="'+t.id+'">'+t.title+'</div>').join(''); $('taskList').querySelectorAll('.task').forEach(el=>el.onclick=()=>{if(!state.unlocked) return openAuth(); map[el.dataset.id]=!map[el.dataset.id]; save(); renderMission(); updateUI();});}
  function switchTab(name){document.querySelectorAll('#tabBar button').forEach(t=>t.classList.toggle('on',t.dataset.tab===name)); ['activity','coaching','visits','actions'].forEach(n=>{const el=$('panel-'+n); if(el) el.classList.toggle('hid', n!==name);});}
  $('tabBar').onclick=e=>{const b=e.target.closest('button'); if(b&&b.dataset.tab) switchTab(b.dataset.tab);};
  document.querySelectorAll('[data-tab]').forEach(b=>{if(b.closest('#tabBar')) return; b.onclick=()=>{if(!state.unlocked) return openAuth(); switchTab(b.dataset.tab);};});
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
  function renderLists(){const box=(id,arr,line)=>{const el=$(id); if(!el) return; el.innerHTML=arr.length?arr.slice().reverse().map(e=>'<div class="task">'+line(e)+' · '+new Date(e.ts).toLocaleString()+'</div>').join(''):'<div class="task">No records yet.</div>';}; box('coachingList',state.coaching,e=>e.name+' · '+e.topic); box('visitsList',state.visits,e=>e.crew+' · '+e.focus); box('actionList',state.actions,e=>e.title); const items=[]; state.coaching.forEach(e=>items.push({ts:e.ts,x:'Coaching · '+e.name})); state.visits.forEach(e=>items.push({ts:e.ts,x:'Visit · '+e.crew})); state.actions.forEach(e=>items.push({ts:e.ts,x:'Action · '+e.title})); items.sort((a,b)=>b.ts-a.ts); $('activityList').innerHTML=items.length?items.slice(0,30).map(i=>'<div class="task">'+i.x+' · '+new Date(i.ts).toLocaleString()+'</div>').join(''):'<div class="task">Activity appears as you log work.</div>';}
  function gate(fn){return e=>{e.preventDefault(); if(!state.unlocked) return openAuth(); fn(); save(); renderLists(); updateUI(); e.target.reset();};}
  $('coachingForm').onsubmit=gate(()=>state.coaching.push({id:uid(),name:$('coachName').value.trim(),topic:$('coachTopic').value,notes:$('coachNotes').value.trim(),ts:Date.now()}));
  $('visitForm').onsubmit=gate(()=>state.visits.push({id:uid(),crew:$('visitCrew').value.trim(),focus:$('visitFocus').value,notes:$('visitNotes').value.trim(),ts:Date.now()}));
  $('actionForm').onsubmit=gate(()=>state.actions.push({id:uid(),title:$('actionTitle').value.trim(),owner:$('actionOwner').value.trim(),done:false,ts:Date.now()}));
  const dlg=$('authDialog');
  function openAuth(){$('authError').textContent=''; $('passwordInput').value=''; dlg.showModal();}
  $('unlockBtn').onclick=openAuth; $('unlockBtn2').onclick=openAuth; $('lockBtn').onclick=()=>setUnlocked(false); $('authCancel').onclick=()=>dlg.close();
  $('authForm').onsubmit=e=>{e.preventDefault(); if($('passwordInput').value===PASS){setUnlocked(true); dlg.close();} else $('authError').textContent='Incorrect password.';};
  $('exportJsonBtn').onclick=()=>{const o=$('payloadOut'); o.classList.remove('hid'); o.value=JSON.stringify({meta:{app:'HB SMOS',v:'2'},state:{tasks:state.tasks,coaching:state.coaching,visits:state.visits,actions:state.actions}},null,2);};
  $('importBtn').onclick=()=>$('importInput').click();
  $('importInput').onchange=e=>{const f=e.target.files[0]; if(!f) return; const r=new FileReader(); r.onload=ev=>{try{const j=JSON.parse(ev.target.result); const src=j.state||j; Object.assign(state,{tasks:src.tasks||{},coaching:src.coaching||[],visits:src.visits||[],actions:src.actions||[]}); save(); renderMission(); renderLists(); updateUI(); alert('Import complete');}catch(err){alert('Bad JSON');}}; r.readAsText(f);};
  $('clearWeekBtn').onclick=()=>{if(!state.unlocked) return openAuth(); if(!confirm('Reset week data on this device?')) return; state.tasks={}; state.coaching=[]; state.visits=[]; state.actions=[]; save(); renderMission(); renderLists(); updateUI();};
  $('voiceBtn').onclick=()=>{const S=window.SpeechRecognition||window.webkitSpeechRecognition; if(!S) return alert('Voice needs Chrome.'); if(!state.unlocked) return openAuth(); const rec=new S(); rec.lang='en-US'; rec.onresult=ev=>{const t=ev.results[0][0].transcript.toLowerCase(); if(t.includes('visit')) state.visits.push({id:uid(),crew:'Voice',focus:'QA',notes:t,ts:Date.now()}); else state.coaching.push({id:uid(),name:'Voice',topic:'Leadership',notes:t,ts:Date.now()}); save(); renderLists(); updateUI();}; rec.start();};
  function initMesh(){const canvas=$('opsMesh'); if(!canvas) return; const ctx=canvas.getContext('2d'); const nodes=[{x:.2,y:.45,c:'#00ff87'},{x:.5,y:.25,c:'#60efff'},{x:.8,y:.45,c:'#ff0080'},{x:.5,y:.75,c:'#ffcc00'}]; const edges=[[0,1],[1,2],[0,3],[1,3],[2,3]]; const parts=Array.from({length:28},(_,i)=>({e:i%5,t:Math.random(),s:.005})); function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2); canvas.width=r.width*d; canvas.height=r.height*d; ctx.setTransform(d,0,0,d,0,0);} resize(); addEventListener('resize',resize); (function frame(){requestAnimationFrame(frame); const w=canvas.getBoundingClientRect().width,h=canvas.getBoundingClientRect().height; ctx.clearRect(0,0,w,h); edges.forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(nodes[a].x*w,nodes[a].y*h);ctx.lineTo(nodes[b].x*w,nodes[b].y*h);ctx.strokeStyle='rgba(0,255,135,.2)';ctx.stroke();}); parts.forEach(p=>{p.t+=p.s; if(p.t>1){p.t=0;p.e=(p.e+1)%edges.length;} const [a,b]=edges[p.e]; ctx.beginPath(); ctx.arc((nodes[a].x+(nodes[b].x-nodes[a].x)*p.t)*w,(nodes[a].y+(nodes[b].y-nodes[a].y)*p.t)*h,2,0,Math.PI*2); ctx.fillStyle=nodes[a].c; ctx.fill();}); nodes.forEach(n=>{ctx.beginPath();ctx.arc(n.x*w,n.y*h,6,0,Math.PI*2);ctx.fillStyle=n.c;ctx.fill();});})();}
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
  setUnlocked(!!state.unlocked); renderDays(); renderMission(); renderLists(); updateUI(); initMesh();
})();
